### ISSUE TITLE
How to obtain the ground truth scene coordinates?

### ISSUE THREAD

**Issue by jasonlovescoding** [vislearn/esac#1]
Hi Eric,

I've installed esac extension and set up 7scenes dataset. Then in `/esac/environments/7scenes` I run

```
python ../../code/init_gating.py
```
The error pops up

```
Traceback (most recent call last):
  File "../../code/init_gating.py", line 36, in <module>
    trainset = RoomDataset("training")
  File "/esac/code/room_dataset.py", line 86, in __init__
    cur_init = os.listdir(scene + '/' + init_dir)
FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/7scenes_chess/training/init/'
```
It seems that the ground truth scene coordinates are not set up with the dataset. 
From the error log I guess it is because the dataset link for that part is down. (Same for the links of the pre-trained models). When I visit that link from a browser, it shows

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```
Could you take a look? Thanks!

Best regards,

Qianhao

**Comment by ebrach** [comment]
Hi Qianhao,

it seems the cloud space of the TU Dresden is offline at the moment. It is not just my links, but the whole system. I can do nothing about that at the moment. Let's hope they fix it soon.

**Comment by jasonlovescoding** [comment]
Hi @ebrach ,

thanks for the reply! The server has been back online now. I guess it just took a weekend off :)
