### ISSUE TITLE
convert to onxx

### ISSUE THREAD

**Issue by mohsen0311** [vislearn/esac#2]
hi i want to use your code as pose estimation in my university project is there any chance that can use it as online  (use it for every frame of a scene ). my project is in unity3d i can convert my pytorch models as onxx to unity and use it perfectly online .is there any chance that i can convert your models to onxx format ? by the way great work tank you for sharing it here .its helps a lot

**Comment by ebrach** [comment]
Hi,

I did not try to convert models to onxx myself, so I'm afraid I cannot help you with that. Let me know what you find out :-)

Regarding using it online: It depends on the hardware whether the prediction would be fast enough if you want interactive frame rates. You can of course play around with the network architecture for the experts. I have good experience  with just reducing the number of channels per layer to make the networks smaller and faster. Another way to accelerate things is to reduce the image resolution before passing it to the pipeline. This will also accelerate the pose estimation part of the code. For pose estimation, reducing the number of RANSAC hypotheses will also help with speed. 

But be aware that changing the network architecture and properties like input resolution requires you to retrain all networks.

Also (you might be aware of this): ESAC is a re-localization method that is trained for a specific scene. You can only deploy it in the scenes it has been trained for. Not sure whether this fits well into your university project.

Best,
Eric

**Comment by ebrach** [comment]
Closing this old issue.
