### ISSUE TITLE
"import esac" error

### ISSUE THREAD

**Issue by Okityou** [vislearn/esac#3]
Hi Eric,

I've successfully installed esac extension according to your steps, but when I try to "import esac" in python scripts, one error popped up:
![image](https://user-images.githubusercontent.com/44048634/79529825-3923ed80-80a0-11ea-8344-7cc6eba7181a.png)

It doesn't look like any packages are missing. Is it because some packages are not compatible? I'm confused. Could you take a look? By the way, thank you for your work and your sharing.

Best regards,
Ling

**Comment by ebrach** [comment]
Hi Ling,

I'm not completely sure what the problem is. It seems the ESAC module has no access to the PyTorch library - the undefined symbol hints towards caffe2 which is part of PyTorch. "import torch" works?

**Comment by Okityou** [comment]
Yes, it works.

**Comment by ebrach** [comment]
Well, my best guess would be package incompatibility as you suggest. If you are using the latest version of PyTorch, I would first try a fresh install (in a new conda env) of the PyTorch version specified in the readme. 

Another thing to make sure: Is the compiler of the ESAC extension accessing the same PyTorch version you are using at runtime? In case you have multiple versions of PyTorch installed on your system, I could imagine that the C++ compiler uses a different one from the version of the current conda env.

**Comment by Okityou** [comment]
Thank you for your reply. I found that pytorch1.2.0 is incompatible with some packages in my environment. Later, I tried other versions of pytorch and succeeded. Thank you again.
